### ISSUE TITLE
Add `swapTVar` to `MonadSTM`

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#1063]

**Comment by coot** [comment]
Done in #2580

**Comment by mrBliss** [comment]
@coot I don't think this is done (not in #2580): https://github.com/input-output-hk/ouroboros-network/search?q=swapTVar

**Comment by coot** [comment]
You're right, I probably confused it with `swapTMVar` (which is around for some time).

**Comment by coot** [comment]
This is already done.
