### ISSUE TITLE
File descriptor limits

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#1250]
The goal is to avoid the possibility of the node crashing due to exhausting file descriptor limits.

We can use http://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Resource.html#v:setResourceLimit to change soft & hard limits if the process is allowed to do so:
```
setSensibleOpenFilesLimit sensibleLimit = do
    limit@ResourceLimit{hardLimit} <- getResourceLimit ResourceOpenFiles
    setResourceLimit ResourceOpenFiles limit{softLimit = min sensibleLimit hardLimit}
```

**Comment by dcoutts** [comment]
We will also need to do an analysis and tests of how a node behaves when it is near its file descriptor limit. We'll probably need to count descriptors used per client and use that to have a client limit, leaving enough for shared descriptors.

**Comment by mrBliss** [comment]
For consensus, see #1396 and #1397.

**Comment by coot** [comment]
This is done in #4585.
