### ISSUE TITLE
IOSimPOR diffusion tests

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#3617]
Currently, we don't yet have diffusion tests, but it would be good to have test which cover both outbound governor, e.g.
* [x] "no fail" property test
* [x] "no livelock" property test

The following inbound governor tests:
* [x] `prop_inbound_governor_valid_transition_order`
* [x] `prop_inbound_governor_valid_transition_order`

The following connection manager tests:
* [x] `prop_inbound_governor_valid_transition_order`
* [x] `prop_inbound_governor_valid_transition_order`

Other tests which would be interesting to have (just a dip of the iceberg):
* [x] `prop_timeouts_enforced`
* [x] `prop_never_above_hardlimit`

**Comment by bolt12** [comment]
Done in: https://github.com/IntersectMBO/ouroboros-network/pull/4872
