### ISSUE TITLE
Publish Simulated File System on Hackage

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#4082]
[Test.Ouroboros.Storage.FS](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/FS/StateMachine.hs) introduces a general framework for testing components which depend on file system APIs.

**Comment by jorisdral** [comment]
`fs-api-0.1.0.0` and `fs-sim-0.1.0.0` have been released to CHaP

**Comment by coot** [comment]
Published: https://hackage.haskell.org/package/fs-sim
