### ISSUE TITLE
Remove `knownLedgerPeer :: IsLedgerPeer` record field from `KnownPeerInfo`

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#4719]
Peers that are coming from ledger are added to `publicRootPeers` or `bigLedgerPeers` record fields of `PeerSelectionState`.  We we will also include public roots from the topology file to `publicRootPeers`, but these are supposed to be ledger peers, so there's no need to maintain `IsLedgerPeer` as part of `KnownPeerInfo`.

**Comment by bolt12** [comment]
This is addressed in bootstrap peers PR if I am not mistaken 🙂
