### ISSUE TITLE
Analyse TVar memory leak when using `ghc-9.8`

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#4776]
One can reproduce the problem with this [repo](https://github.com/erikd/tvar-memleak-test).

We know the problem is caused by pipelining, especially when maximal pipelining depth is heigh.  Some ideas to simplify the repository:

1. eliminate `cpsVar`
2. swap `doneVar` for an `MVar`
3. eliminate `Channel` and use [`connectPipelined`](https://input-output-hk.github.io/typed-protocols/typed-protocols/Network-TypedProtocol-Proofs.html#v:connectPipelined) instead,
4. eliminate usage of typed-protocols, and run `ChainSyncServer` against `ChainSyncClientPipelined` against each other with: [directPipelined](https://github.com/IntersectMBO/ouroboros-network/blob/master/ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/ChainSync/DirectPipelined.hs#L12-L17).
5. simplify `chain-sync` protocol

**Comment by coot** [comment]
We found out that the memory leak was resolved when the number of pipelined messages  was reduced to a small number.  There's more information about it in an unfortunately private [slack thread](https://input-output-rnd.slack.com/archives/CDA6LUXAQ/p1704410155610919).

**Comment by bolt12** [comment]
[tvar-memleak-test.zip](https://github.com/IntersectMBO/ouroboros-network/files/15093013/tvar-memleak-test.zip)

The repo above no longer exists but was saved
