### ISSUE TITLE
Pull configuration values to ouroboros-network

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#4805]
There are various default configuration values defined in different places.  I suggest we provide:
```
Ouroboros.Network.Diffusion.Configuration
```
module in  `ouroboros-network` which provides them.  Some of the defaults are defined in
* [cardano-node](https://github.com/IntersectMBO/cardano-node/blob/master/cardano-node/src/Cardano/Node/Configuration/POM.hs#L484-L526) and include:
  * `pncProtocolIdleTimeout`
  * `pncTimeWaitTimeout`
  * `pncAcceptedConnectionsLimit`
  * `pncTargetNumberOfRootPeers`
  * `pncTargetNumberOfKnownPeers`
  * `pncTargetNumberOfEstablishedPeers`
  * `pncTargetNumberOfActivePeers`
  * `pncTargetNumberOfKnownBigLedgerPeers`
  * `pncTargetNumberOfEstablishedBigLedgerPeers`
  * `pncTargetNumberOfActiveBigLedgerPeers`
  * `pncEnableP2P`
  * `pncPeerSharing`
  
from `ouroboros-network`:
  * `Ouroboros.Network.NodeToNode.defaultMiniProtocolParameters` which is used in [`miniProtocolParameters`](https://github.com/IntersectMBO/ouroboros-consensus/blob/a6e6707974d12fecd40650e6fb995d2058772d37/ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs#L667)
  * some values defined in [`Ouroboros.Network.Diffusion.Policies`](https://github.com/IntersectMBO/ouroboros-network/blob/f83f71ad674721605efa0f31cf2144cc6dd5dd4d/ouroboros-network/src/Ouroboros/Network/Diffusion/Policies.hs#L4) should be moved to the new module:
    * `deactivateTimeout`
    * `closeConnectionTimeout`
    * `peerMetricsConfiguration`

from `ouroboros-consensus`:
  * [`defaultBlockFetchConfiguration`](https://github.com/IntersectMBO/ouroboros-consensus/blob/a6e6707974d12fecd40650e6fb995d2058772d37/ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs#L672-L679)
  * [`stdChainSyncTimeout`](https://github.com/IntersectMBO/ouroboros-consensus/blob/a6e6707974d12fecd40650e6fb995d2058772d37/ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs#L724-L749)

**Comment by coot** [comment]
As of implementation it might be good idea to group all the `outbound-governor` related targets (e.g. `pncTargetNumber...`) group in a single record.  For other we could provide `newtype` wrappers, especially if that turns out to be beneficial for `ouroboros-network` too - the advantage of this is that who ever is doing top level plumbing in `cardano-node` (or elsewhere, which currently doesn't exist :grin:) will be assisted by the compiler.

**Comment by coot** [comment]
There's possibly one more config value which goes into the `outbound-governor` default configuration: the default number of bootstrap peers.

**Comment by coot** [comment]
Peer sharing configuration values than could be moved too, [ref](https://github.com/IntersectMBO/ouroboros-network/commit/020fda4ffeeea7730d5819c8c14ac3976c38fcc8#diff-837906e54b9a2617fc95a7fb09b4156c1210ee9086f52a319047861d35b0c8b8R147-R156).

**Comment by crocodile-dentist** [comment]
will do
