### ISSUE TITLE
FR - Whitelisting internal/external infrastructure IPs/Networks in the config to bypass connection limits

### ISSUE THREAD

**Issue by gitmachtl** [IntersectMBO/ouroboros-network#4894]
Now with P2P, many SPOs are seeing high connection numbers. My relays for example are hitting the 500+ mark pretty easy for incoming connections. Which results in the strange behavior, that i cannot even do my own healthcheck cncli/cardano-cli pings to the node, because its full.

We can set a lower threshold now in the config, but that only helps so much that the limit is reached faster for that case. Maybe lower node load on systems with lower hardware specs yes, but still the problem is, that we cannot contact the node in that situation with our own gear.

Would it be possible to get some intelligence directly in the node so we can define "whitelisted" ip's/networks/dns-entries in an extra section of the topology.json file? So in case of hitting the set connection limit amount, the node is first checking the source address of an incoming connection, and if it matches an entry in the config it gets passed thru. Other nodes are still limited by the connection limit set in the config like now.

That way we could define IP addresses/networks(f.e. 10.0.0.0/8)/dns-entries that are our own infrastructure, public or via vpn. And even when a node hits a set limit of incoming connections, we could still connect to it with our own stuff. Same goes for the explorers and 3rd party tools out there running health checks. If they provide addresses, we could set them in the config and so cexplorer, adastat, cardanoscan, etc... can do there healthcheck and get a positiv response, even the node is limiting other nodes to a set number of connections. Using DNS entries for the whitelisting would help 3rd party tools/explorers to update there IPs without an interaction needed by the SPOs. The DNS entries just needs to be resolved on a regular interval by the node. I think we could reuse existing logic here from the Public/Private/Bootstrap peer section in the topology.

I did some testing by using the firewall of the machine itself to do the limitation, and whitlisting own connections like:
```
-A INPUT -s <ownIPs> -p tcp -m tcp --dport 3001 --tcp-flags FIN,SYN,RST,ACK SYN -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3001 --tcp-flags FIN,SYN,RST,ACK SYN -m connlimit --connlimit-above 400 --connlimit-mask 0 --connlimit-daddr -j REJECT --reject-with tcp-reset
```
That is working fine, but its really host system depending and difficult to setup for most SPOs. Having a solution directly within the node would make it way more easier.

The "whitelisting" again would not only help to get node-pings thru to the node, it would also allow the normal N2N connection from own infrastructure to the node in case of a connection limit.

Extra-Feature: If the logic is there, it would also provide the possibility to do a "blacklisting" too. Like setting a blacklisting entry to `0.0.0.0/0` would block all incoming connections, only the ones set in the "whitelisting" section would be allowed to fully connect to the node.

Thanks!

**Comment by bolt12** [comment]
Hi @gitmachtl !

Thanks for writing this out! After reading it and acknowledging that indeed this would be useful for SPOs to be able to do I gave it a quick thought. Unfortunately, I don't think this is really feasible in user space and your workaround using firewall is the way to go since this needs to be managed in kernel space. There's no way to know the IP of the incoming connection up front without accepting it, so this would mean jeopardizing the current incoming connection rate limit and expose the node to resource attacks.

**Comment by gitmachtl** [comment]
Thanks for the comment, i appreciate it. From my POV, you can always DDOS a system. But you could also DDOS a node that is not limiting incoming connections by doing rapid connection/reset patterns. So the question is if it would really be a problem if the node would accept one new incoming connection (after the set limit), checks its source address, and decide afterwards to keep the connection or to drop it. Doing such a check on one new connection could also be rate limited. I'll let you guys think about it. Best regards, Martin

**Comment by bolt12** [comment]
Yes, right now when the node hits the incoming connection hard limit it simply _won't accept_ new connections so attackers won't be able to repeatedly try to connect to it and affect the node, that's what makes the rate limit effective otherwise it wouldn't be safeguarding against anything at all.

**Comment by gitmachtl** [comment]
Well, but an "attacker" could repeatedly try to connect to the node even before the node hits the hard limit? Or even doing hundrets of connections to drive the node into the hard limit. I think we can agree that you can bring a node down if you really want as an attacker. So far i have not heards of or seen any evidence that such a thing actually occured in the past on cardano-nodes?

**Comment by bolt12** [comment]
You are correct, but that's not the only reason to have an inbound rate limit. It is also to bound the resource usage of the node so that an attacker can not make thousand of meaningless incoming connections and exhaust all the available file descriptors. There's no silver bullet I agree, however I don't think that the security tradeoff is worth while when the appropriate way to do it is via kernel space and firewall rules.

Of course we'd like to be able to provide this for SPOs to make life easier for them, if there's a way to do it without compromising the guarantees of the current solution we can consider it! 😄

**Comment by coot** [comment]
We decided against such a feature in `cardano-node`.

Note that having too many inbound connections might actually mean that one is running too few relays with respect to the stake that is behind them.  P2P nodes are using stake distribution to connect to peers.  We now also have a second mechanism - peer sharing, but still stake distribution will be a key factor; for peer sharing to be so effective your relays must be really well positioned in the network, which might require non standard setup (more resources, more outbound connections).
