### ISSUE TITLE
Missing Documentation per OSC Governance

### ISSUE THREAD

**Issue by Ranchhand87** [IntersectMBO/ouroboros-network#4902]
The following Required docs are missing and should show on the Main page of Code: CODEOWNERS, CHANGELOG.md
If there are CHANGELOG's please create a top level file and link accordingly.

The following documents/features are suggested by OSC Governance: Issue Template

For Reference: https://intersect.gitbook.io/open-source-committee/policies/governance
Also see Documentation and Legal

**Comment by Ranchhand87** [comment]
Please provide an update. Thank you!

**Comment by coot** [comment]
I think we resolved the issue on slack, please re-open if it's not the case.
