### ISSUE TITLE
Test failure: node never uses non-trustable peers in clean state

### ISSUE THREAD

**Issue by karknu** [IntersectMBO/ouroboros-network#4942]
CI test failure:
```
sim-tests --quickcheck-replay="(SMGen 1055325783478325567 18154453325318164197,92)" -p '/node never uses non-trustable peers in clean state/'
```

**Comment by crocodile-dentist** [comment]
So the problem occurs when a target for known peers is decreased and a trusted local root peer is dropped immediately. This peer stays in the known peers set until another action in the governor sweeps it out, but until that happens the test logic is written such that it is flagged as an error when known peers /= trusted peers, even if for a brief while.
