### ISSUE TITLE
Extend MuxApplication to be able to take care of resource handling

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#676]
In the context of `startMux`, when it starts all the treads, run a supplied `bracket` like function and share the created resources with spawned threads.  This way we could run `bracketFetchClient` to create and share `FetchClientContext` in `chain-sync` and `block-fetch` mini-protocols.

**Comment by dcoutts** [comment]
If we use the p2p governor, and do the mux refactoring we'll probably want to include this.
